In [4]:
# 1️⃣ Basic Data Understanding
# load the dataset

import pandas as pd

df = pd.read_csv("tips.csv")

In [5]:
# view first rows

df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [6]:
# view last rows

df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [7]:
# shape of dataset

df.shape

(244, 7)

In [8]:
# column names

df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [9]:
# data types

df.dtypes

total_bill    float64
tip           float64
sex               str
smoker            str
day               str
time              str
size            int64
dtype: object

In [10]:
# dataset info

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 13.5 KB

In [11]:
# 2️⃣ Data Cleaning Operations
# check missing values

df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [12]:
# check duplicates

df.duplicated().sum()

np.int64(1)

In [13]:
# remove duplicates (if any)

df = df.drop_duplicates()

In [14]:
# 3️⃣ Statistical Analysis
# Descriptive statistics

df.describe()

       total_bill         tip        size
count  243.000000  243.000000  243.000000
mean    19.813868    3.002387    2.572016
std      8.910071    1.385002    0.952356
min      3.070000    1.000000    1.000000
25%     13.380000    2.000000    2.000000
50%     17.810000    2.920000    2.000000
75%     24.175000    3.575000    3.000000
max     50.810000   10.000000    6.000000

In [15]:
# mean tip

df['tip'].mean()

np.float64(3.00238683127572)

In [16]:
# median total bill

df['total_bill'].median()

np.float64(17.81)

In [17]:
# Maximum tip

df['tip'].max()

np.float64(10.0)

In [18]:
# Minimum tip

df['tip'].min()

np.float64(1.0)

In [19]:
# 4️⃣ GroupBy Operations
# Average tip by gender

df.groupby('sex')['tip'].mean()

sex
Female    2.843140
Male      3.089618
Name: tip, dtype: float64

In [20]:
# Average total bill by day

df.groupby('day')['total_bill'].mean()

day
Fri     17.151579
Sat     20.441379
Sun     21.410000
Thur    17.759508
Name: total_bill, dtype: float64

In [21]:
# Average tip by smoker

df.groupby('smoker')['tip'].mean()

smoker
No     2.991854
Yes    3.019674
Name: tip, dtype: float64

In [22]:
# Total revenue by day

df.groupby('day')['total_bill'].sum()

day
Fri      325.88
Sat     1778.40
Sun     1627.16
Thur    1083.33
Name: total_bill, dtype: float64

In [23]:
# Average tip by time (Lunch/Dinner)

df.groupby('time')['tip'].mean()

time
Dinner    3.102670
Lunch     2.738955
Name: tip, dtype: float64

In [24]:
# 5️⃣ Filtering Operations
# Tips greater than 5

df[df['tip'] > 5]

     total_bill    tip     sex smoker   day    time  size
23        39.42   7.58    Male     No   Sat  Dinner     4
44        30.40   5.60    Male     No   Sun  Dinner     4
47        32.40   6.00    Male     No   Sun  Dinner     4
52        34.81   5.20  Female     No   Sun  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
85        34.83   5.17  Female     No  Thur   Lunch     4
88        24.71   5.85    Male     No  Thur   Lunch     2
116       29.93   5.07    Male     No   Sun  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
155       29.85   5.14  Female     No   Sun  Dinner     5
170       50.81  10.00    Male    Yes   Sat  Dinner     3
172        7.25   5.15    Male    Yes   Sun  Dinner     2
181       23.33   5.65    Male    Yes   Sun  Dinner     2
183       23.17   6.50    Male    Yes   Sun  Dinner     4
211       25.89   5.16    Male    Yes   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3
239       29.03   5.92    Male     No   Sat  Dinner     3

In [25]:
# Non-smokers only

df[df['smoker'] == 'No']

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
235       10.07  1.25    Male     No   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[151 rows x 7 columns]

In [26]:
# Dinner time data only

df[df['time'] == 'Dinner']

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[176 rows x 7 columns]

In [27]:
# Large group size (>4)

df[df['size'] > 4]

     total_bill   tip     sex smoker   day    time  size
125       29.80  4.20  Female     No  Thur   Lunch     6
141       34.30  6.70    Male     No  Thur   Lunch     6
142       41.19  5.00    Male     No  Thur   Lunch     5
143       27.05  5.00  Female     No  Thur   Lunch     6
155       29.85  5.14  Female     No   Sun  Dinner     5
156       48.17  5.00    Male     No   Sun  Dinner     6
185       20.69  5.00    Male     No   Sun  Dinner     5
187       30.46  2.00    Male    Yes   Sun  Dinner     5
216       28.15  3.00    Male    Yes   Sat  Dinner     5

In [28]:
# 6️⃣ New Column Creation
# Create tip percentage column

df['tip_percent'] = (df['tip'] / df['total_bill']) * 100

In [29]:
# Categorize tip (Low/Medium/High)

df['tip_category'] = pd.cut(df['tip'],
                        bins=[0,3,6,10],
                        labels=['Low','Medium','High'])

In [30]:
# 7️⃣ Sorting
# Sort by highest tip

df.sort_values(by='tip', ascending=False)

,total_bill,tip,sex,smoker,day,time,size,tip_percent,tip_category
170,50.81,10.00,Male,Yes,Sat,Dinner,3,19.681165,High
212,48.33,9.00,Male,No,Sat,Dinner,4,18.621974,High
23,39.42,7.58,Male,No,Sat,Dinner,4,19.228818,High
59,48.27,6.73,Male,No,Sat,Dinner,4,13.942407,High
141,34.30,6.70,Male,No,Thur,Lunch,6,19.533528,High
...,...,...,...,...,...,...,...,...,...
0,16.99,1.01,Female,No,Sun,Dinner,2,5.944673,Low
111,7.25,1.00,Female,No,Sat,Dinner,1,13.793103,Low
92,5.75,1.00,Female,Yes,Fri,Dinner,2,17.391304,Low
67,3.07,1.00,Female,Yes,Sat,Dinner,1,32.573290,Low
236,12.60,1.00,Male,Yes,Sat,Dinner,2,7.936508,Low

In [31]:
# Sort by total bill

df.sort_values(by='total_bill')

,total_bill,tip,sex,smoker,day,time,size,tip_percent,tip_category
67,3.07,1.00,Female,Yes,Sat,Dinner,1,32.573290,Low
92,5.75,1.00,Female,Yes,Fri,Dinner,2,17.391304,Low
111,7.25,1.00,Female,No,Sat,Dinner,1,13.793103,Low
172,7.25,5.15,Male,Yes,Sun,Dinner,2,71.034483,Medium
149,7.51,2.00,Male,No,Thur,Lunch,2,26.631158,Low
...,...,...,...,...,...,...,...,...,...
182,45.35,3.50,Male,Yes,Sun,Dinner,3,7.717751,Medium
156,48.17,5.00,Male,No,Sun,Dinner,6,10.379905,Medium
59,48.27,6.73,Male,No,Sat,Dinner,4,13.942407,High
212,48.33,9.00,Male,No,Sat,Dinner,4,18.621974,High
170,50.81,10.00,Male,Yes,Sat,Dinner,3,19.681165,High

In [32]:
# 8️⃣ Value Counts
# Count males & females

df['sex'].value_counts()

sex
Male      157
Female     86
Name: count, dtype: int64

In [33]:
# Count smokers vs non-smokers

df['smoker'].value_counts()

smoker
No     151
Yes     92
Name: count, dtype: int64

In [34]:
# Count by day

df['day'].value_counts()

day
Sat     87
Sun     76
Thur    61
Fri     19
Name: count, dtype: int64

In [35]:
# 9️⃣ Correlation Analysis
# Correlation matrix

df.corr(numeric_only=True)

             total_bill       tip      size  tip_percent
total_bill     1.000000  0.674998  0.597589    -0.339400
tip            0.674998  1.000000  0.488400     0.342408
size           0.597589  0.488400  1.000000    -0.143252
tip_percent   -0.339400  0.342408 -0.143252     1.000000

In [36]:
# Correlation between total_bill and tip

df['total_bill'].corr(df['tip'])

np.float64(0.6749978565456074)

In [37]:
# 🔟 Aggregation with Multiple Columns
# Mean tip and bill by day & time

df.groupby(['day','time'])[['total_bill','tip']].mean()

             total_bill       tip
day  time
Fri  Dinner   19.663333  2.940000
     Lunch    12.845714  2.382857
Sat  Dinner   20.441379  2.993103
Sun  Dinner   21.410000  3.255132
Thur Dinner   18.780000  3.000000
     Lunch    17.742500  2.780500

In [38]:
# 1️⃣1️⃣ Pivot Table
# Pivot table of average tip

pd.pivot_table(df,
               values='tip',
               index='day',
               columns='sex',
               aggfunc='mean')

sex     Female      Male
day
Fri   2.781111  2.693000
Sat   2.801786  3.083898
Sun   3.367222  3.220345
Thur  2.594194  2.980333

In [39]:
# 1️⃣2️⃣ Export Processed Data
# Save updated dataset

df.to_csv("tips_processed.csv", index=False)